title: "Apoorvi Sharma"
author: "Apoorvi S."
description: "A. Sharma © 2023"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_social: true 
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true            # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "HOME", icon: home}
  - {file: "About.md", title: "ABOUT", icon: address-card}
  - {url: "/Apoorvi.pdf", title: "CV", icon: file}


external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:apoorvisharma.2909@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/Apoorvi-29"}


comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
